tables:
  - name: users
    columns:
      - name: id
        data_type: SERIAL
        is_primary: true
        is_nullable: false
      - name: username
        data_type: VARCHAR(50)
        is_nullable: false
        default: "'guest'"
      - name: created_at
        data_type: TIMESTAMP
        is_nullable: false
        default: "NOW()"
    indexs:
      - name: idx_username
        columns: 
          - username
        unique: true

  - name: posts
    columns:
      - name: id
        data_type: SERIAL
        is_primary: true
        is_nullable: false
      - name: user_id
        data_type: INTEGER
        is_nullable: false
      - name: content
        data_type: TEXT
        is_nullable: false
    indexs:
      - name: idx_user_id
        columns: 
          - user_id
